// client/src/components/Cadastro.tsx
import GenericInput from "./GenericInput";

type Props = { name: string };

const Cadastro = (props: Props) => {
	return (
		<form action="">
			<h1>Vamos criar sua conta</h1>
			<GenericInput
				type="email"
				placeholder="Ex: sara@gmail.com"
				labelText="Email"
				name="email"
			/>
			<GenericInput
				type="password"
				placeholder="Digite a sua senha"
				labelText="Digite a sua senha"
				name="password1"
			/>
			<GenericInput
				type="password"
				placeholder="Digite a sua senha novamente"
				labelText="Confirme a sua senha"
				name="password2"
			/>
			<div>
				<p>Você quer se cadastrar como ?</p>
				<div>
					<div>
						<input
							type="radio"
							name="empresa-chk"
							id="empresa-chk"
							value={"empresa"}
						/>
						<label htmlFor="empresa-chk">Empresa</label>
					</div>
				</div>
			</div>
		</form>
	);
};

export default Cadastro;

// frontend/src/app/components/pages/cadastro/cadastro.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-cadastro',
  templateUrl: './cadastro.component.html',
  styleUrl: './cadastro.component.css',
})
export class CadastroComponent {
  tipoCadastro: string = '';
}

<section>
  <div class="container-login">
    <img class="logo" src="/assets/imgs/logo.svg" alt="" />
    <form>
      <h2>Vamos criar sua conta</h2>
      <div class="form-container">
        <label for="email">Email</label>
        <input
          formControlName="email"
          type="text"
          placeholder="Digite o seu email"
        />
      </div>
      <div class="form-container">
        <label for="password">Senha</label>
        <input
          formControlName="password"
          type="password"
          placeholder="Digite a sua senha"
        />
      </div>
      <div class="form-container">
        <label for="password">Senha</label>
        <input
          formControlName="password"
          type="password"
          placeholder="Digite a sua senha"
        />
      </div>
      <div class="form-container">
        <label for="password">Você quer se canditar como</label>
        <div class="container-checkboxes">
          <div>
            <input type="checkbox" name="" id="" />
            <label for="empresa-input">Empresa</label>
          </div>
          <div>
            <input
              type="checkbox"
              name="restaurante-input"
              id="restaurante-input"
            />
            <label for="restaurante-input">Restaurante</label>
          </div>
        </div>
      </div>
      <button class="btn-entrar" type="submit" [routerLink]="['/login']">
        Entrar
      </button>
      <button [routerLink]="['/cadastro']" class="btn-cadastrar" type="button">
        Cadastrar
      </button>
      <p class="texto-esqueceu-senha">Esqueci a senha</p>
    </form>
  </div>
</section>
